services:
  - type: web
    name: expense-tracker-api
    runtime: docker
    plan: free
    buildCommand: "dotnet restore && dotnet build"
    startCommand: "dotnet run --urls http://0.0.0.0:$PORT"
    autoDeploy: true
    envVars:
      - key: DOTNET_ENVIRONMENT
        value: Production
      - key: CONNECTION_STRING
        value: "Server=YOUR_SERVER_NAME;Database=YOUR_DB_NAME;User Id=YOUR_USERNAME;Password=YOUR_PASSWORD;TrustServerCertificate=True;Encrypt=False;"

